### ISSUE TITLE
ArcGIS map zooming with mouse wheel is choppy when I try to handle event ViewpointChanged

### ISSUE THREAD

**Issue by rodsantest1** [rodsantest1/ReactiveUI_Journey_Solution#1]
Hi,
I have a subtle issue with map zooming in a prototype that's in this [[repo](https://github.com/rodsantest1/ReactiveUI_Journey_Solution/blob/master/RxuiMvpApp/MainWindow.xaml.cs)]. This particular prototype synchronizes map zoom between zoom buttons, a slider, and the mouse wheel. The issue is when I use mouse wheel to zoom the result is map will zoom and then shift (in the video it's a small shift but on other computers it can be a significant shift). 

I’m using the Viewpoint Changed event to set the map scale.  Any thoughts?

https://user-images.githubusercontent.com/30728121/126724262-a9fcee22-06f9-4ac5-bdbb-8bd573ae141b.mp4

**Comment by rodsantest1** [comment]
https://community.esri.com/t5/arcgis-runtime-sdk-for-net-questions/small-wpf-prototype-that-syncs-zoom-buttons-a/m-p/1082031#M10307

**Comment by rodsantest1** [comment]
Resolved
![image](https://user-images.githubusercontent.com/30728121/126875618-9f5c36a8-b209-4263-a2f6-45d70d73e4b5.png)

**Comment by dotMorten** [comment]
Were you getting into a situation where the view would set the slider, and the slider would set the view scale, which would set the slider which would set the view scale which would.... etc etc? Also consider using the Delay property on the scale binding on your slider.

**Comment by dotMorten** [comment]
> I’m using the Viewpoint Changed event to set the map scale. Any thoughts?

You might want to use the `MapScale` property changed event instead, so it doesn't run that code on pan and rotate where the scale isn't changing. You can also reduce updates by using the `IsNavigating` property to ignore scale changes until the operation is complete.

**Comment by rodsantest1** [comment]
Thanks @dotMorten for the insight.
